
# Simformer Training Configuration

# note: yaml can't resolve 1e-3 as 0.001, so write float numbers explicitly

task_name: two_moons

optimizer:
  patience: 10
  cooldown: 2
  factor: 0.5
  accumulation_size: 100
  rtol: 1.0e-4
  max_lr: 1.0e-3
  min_lr: 1.0e-7

model: 
  in_channels: 1
  dim_value: 40
  dim_id: 40
  dim_condition: 10
  fourier_features: 128
  num_heads: 4
  num_layers: 6
  widening_factor: 3
  qkv_features: 40
  num_hidden_layers: 1

training:
  batch_size: 4096
  nsteps: 10000
  nepochs: 3
  multistep: 1
  early_stopping: true
  print_every: 100
  experiment_id: 3
  restore_model: true
  train_model: false

  total_number_steps_scaling: 3
  max_number_steps: 100000
  min_number_steps: 5000